package Quiz;

import javax.swing.*;
import java.awt.*;

public class QuizUI {

    private JPanel panel1;

    public void startDisplay() {

    }

    public void reset() { //resets the UI

    }

    public void displayQuestion() {  //adds question to label

    }

    public void displayChoices() { // adds possible choices to buttons

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
