package Formulas;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PhysicsFormulasUI {
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JButton button4;
    private JTextPane V0TextArea;
    private JLabel V1Label;
    private JTextPane V1TextArea;
    private JLabel V0Label;
    private JLabel TLabel;
    private JTextPane TTextArea;
    private JLabel ALabel;
    private JTextPane ATextArea;
    private JLabel XiLabel;
    private JTextPane XiTextArea;
    private JLabel XfLabel;
    private JTextPane XfTextArea;
    private JPanel MainPanel;


    public PhysicsFormulasUI() {

        button1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        button2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        button3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        button4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public static void RunPhysicsFormulasUI() {
        JFrame frame = new JFrame("Physics Formulas");
        frame.setContentPane(new PhysicsFormulasUI().MainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridBagLayout());
        button2 = new JButton();
        button2.setText("Button");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(button2, gbc);
        button3 = new JButton();
        button3.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(button3, gbc);
        button4 = new JButton();
        button4.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(button4, gbc);
        V0TextArea = new JTextPane();
        V0TextArea.setBackground(new Color(-9014670));
        V0TextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(V0TextArea, gbc);
        V1TextArea = new JTextPane();
        V1TextArea.setBackground(new Color(-9014670));
        V1TextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(V1TextArea, gbc);
        TTextArea = new JTextPane();
        TTextArea.setBackground(new Color(-9014670));
        TTextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(TTextArea, gbc);
        ATextArea = new JTextPane();
        ATextArea.setBackground(new Color(-9014670));
        ATextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(ATextArea, gbc);
        V1Label = new JLabel();
        V1Label.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(V1Label, gbc);
        V0Label = new JLabel();
        V0Label.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(V0Label, gbc);
        TLabel = new JLabel();
        TLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(TLabel, gbc);
        ALabel = new JLabel();
        ALabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(ALabel, gbc);
        button1 = new JButton();
        button1.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        MainPanel.add(button1, gbc);
        XiTextArea = new JTextPane();
        XiTextArea.setBackground(new Color(-9014670));
        XiTextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(XiTextArea, gbc);
        XfTextArea = new JTextPane();
        XfTextArea.setBackground(new Color(-9014670));
        XfTextArea.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        MainPanel.add(XfTextArea, gbc);
        XiLabel = new JLabel();
        XiLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(XiLabel, gbc);
        XfLabel = new JLabel();
        XfLabel.setText("Label");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.anchor = GridBagConstraints.WEST;
        MainPanel.add(XfLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainPanel;
    }
}
