package Store;
//Created by Eyaad Mir
import Gmail.GmailUI;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.lang.*;
public class Store {
    protected JButton ViewItems;
    protected JButton ViewInventory;
    protected JPanel store;
    protected JLabel welcomeLabel;
    protected JLabel moneyLabel;
    protected static int money = 100;
    protected static int books = 0;
    protected static int cards = 0;

    public static void main(String[] args) { }

    public static void RunStoreUI() {
        // Declaring parts of the main screen
        JFrame frame = new JFrame();
        JButton ViewItems = new JButton("View Items");
        JButton ViewInventory = new JButton("View Inventory");
        JPanel store = new JPanel();
        JLabel welcomeLabel = new JLabel("Welcome to the store!");
        JLabel moneyLabel = new JLabel("You currently have " + money + " dollars");
        store.setLayout(null);

        // Dimensions and properties of Frame
        frame.setSize(600, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        frame.add(store);

        //Setting locations of my buttons and Labels
        ViewItems.setBounds(40, 200, 200, 125);
        ViewInventory.setBounds(340, 200, 200, 125);
        welcomeLabel.setBounds(40, 0, 200, 175);
        moneyLabel.setBounds(40, 400, 200, 175);

        store.add(ViewItems);
        store.add(ViewInventory);
        store.add(welcomeLabel);
        store.add(moneyLabel);

        ViewItems.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Items buy = new Items();
                buy.RunItemsUI();
            }
        });





    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }
}
class Items extends Store {
    private JLabel test;
    private JPanel items;
    private JLabel moneyLabel;
    private JLabel book;
    private JLabel card;
    private JButton buyBook;
    private JButton buyCards;
    private JButton goBack;

    public void RunItemsUI() {
        //Initializing GUI
        JFrame frame = new JFrame();
        JPanel items = new JPanel();
        JLabel test = new JLabel("Buy Items:");
        JLabel book = new JLabel();
        JLabel card = new JLabel();
        JLabel moneyLabel = new JLabel("You currently have " + money + " dollars");
        JButton buyBook = new JButton("Buy Book: $10");
        JButton buyCards = new JButton("Buy Cards: $5");
        JButton goBack = new JButton("Go Back");

        items.setLayout(null);

        // Dimensions and properties of Frame
        frame.setSize(600, 600);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        frame.add(items);

        book.setIcon(new ImageIcon(".\\.\\.\\Icons\\book.jpg"));
        card.setIcon(new ImageIcon(".\\.\\.\\Icons\\cards.jpg"));
        //Setting locations of my buttons and Labels
        test.setBounds(40, 0, 200, 175);
        moneyLabel.setBounds(40, 450, 500, 175);
        buyBook.setBounds(40,120,150,125);
        buyCards.setBounds(40,270,150,125);
        book.setBounds(300,120,175,135);
        card.setBounds(300,270,175,117);
        goBack.setBounds(20,400,120,100);

        //Adding parts to panel
        items.add(book);
        items.add(card);
        items.add(test);
        items.add(buyBook);
        items.add(buyCards);
        items.add(moneyLabel);
        items.add(goBack);


        buyBook.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //For when you don't have enough money
                if (money < 10) {
                    moneyLabel.setText("You do not have enough money for this purchase. You only have " + money + " dollars");
                  //  try {
                        // thread to sleep for 1000 milliseconds
                    //    Thread.sleep(1000);
                    //}  catch (InterruptedException ex) {
                      //  Thread.currentThread().interrupt();
                    //}
                    //moneyLabel.setText("You currently have " + money + " dollars");
                }
                else {
                    money = money - 10;
                    books += 1;
                    moneyLabel.setText("You currently have " + money + " dollars.");
                }
            }
        });
        buyCards.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //For when you don't have enough money
                if (money < 5) {
                    moneyLabel.setText("You do not have enough money for this purchase. You only have " + money + " dollars");
                    //  try {
                    // thread to sleep for 1000 milliseconds
                    //    Thread.sleep(1000);
                    //}  catch (InterruptedException ex) {
                    //  Thread.currentThread().interrupt();
                    //}
                    //moneyLabel.setText("You currently have " + money + " dollars");
                }
                else {
                    money = money - 5;
                    cards += 1;
                    moneyLabel.setText("You currently have " + money + " dollars.");
                }
            }
        });
        goBack.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Store back = new Store();
                back.RunStoreUI();
            }
        });



    }
}

