package ATM;

import CalculatorUI.CalculatorUI;

import javax.print.attribute.standard.JobOriginatingUserName;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class ATM {
    private JPanel ATM;
    private JLabel user;
    private JTextField userfield;
    private JButton login;
    private JPasswordField passfield;
    private JLabel update;
    private JLabel pass;
    String uname;
    String pword;

    public ATM() {
        login.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String uname = userfield.getText();
                String pword = passfield.getText();

                if (uname.equals("NeilSahai") && pword.equals("CSisCool!")) {
                    update.setText("Login Successful!");
                } else {
                    update.setText("Login Unsuccessful, Please try again!");
                }

            }
        });
    }

    public static void main(String[] args) {
        // creating the parts of my login screen
        JFrame frame = new JFrame();
        JPanel ATM = new JPanel();
        JLabel user = new JLabel("Username");
        JLabel pass = new JLabel("Password");
        JTextField userfield = new JTextField();
        JLabel update = new JLabel("Login in with your Credentials!");
        JPasswordField passfield = new JPasswordField();
        JButton login = new JButton("Login!");

        // setting the size and constraints for the login window
        frame.setSize(400, 400);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
        frame.add(ATM);

        // not using a layout to let me freely move my login around
        ATM.setLayout(null);

        //sets the location of the parts of my GUI
        user.setBounds(40, 20, 80, 125);
        pass.setBounds(40, 40, 80, 175);
        passfield.setBounds(125, 120, 150, 15);
        userfield.setBounds(125, 80, 150, 15);
        update.setBounds(115, 150, 200, 15);
        login.setBounds(125, 190, 150, 15);

        //adding the parts of my login function to the JPanel
        ATM.add(user);
        ATM.add(pass);
        ATM.add(userfield);
        ATM.add(update);
        ATM.add(passfield);
        ATM.add(userfield);
        ATM.add(login);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ATM = new JPanel();
        ATM.setLayout(new GridBagLayout());
        user = new JLabel();
        user.setText("Username");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        ATM.add(user, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ATM.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        ATM.add(spacer2, gbc);
        pass = new JLabel();
        pass.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        ATM.add(pass, gbc);
        userfield = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ATM.add(userfield, gbc);
        passfield = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ATM.add(passfield, gbc);
        login = new JButton();
        login.setText("Login");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ATM.add(login, gbc);
        update = new JLabel();
        update.setText("Login with your Credentials");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        ATM.add(update, gbc);
        pass.setLabelFor(passfield);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ATM;
    }

}



