//Part of Andrew's Project
//I was trying to create a main menu where you could select games and it would open a new JFrame
//On the student led forum, I saw one of the groups use a card layout, so I'll probably use that instead

package Games;

import javax.swing.*;
import java.awt.*;

public class Games {

    private JPanel panel1;

    public static void main(String[] args) {
        System.out.println(":/");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
